export const items = [
  {
    id: 7,
    weight: 0.4,
    name: "Collectible Malls",
    parent: "Collectible Malls",
    stats: {
      motivation: "Desi",
      probability: "Prob",
    },
    description: "“Once a thriving marketplace, this digital hub now exists in the endless corners of virtual space, a labyrinth of forgotten treasures. Though it's less exclusive than before, some collectors still seek the hidden gems among the endless shelves.“",
    thumbnail: "./logo192.png",
    artwork: "./mov/CollectibleMalls/CollectibleMalls.mp4",
    color: "--color-future-market",
    passkit: "./passes/testwallet.pkpass",
  },
  {
    id: 1,
    weight: 0.6,
    name: "Mystery Vending Machine",
    parent: "Collectible Malls",
    stats: {
      motivation: "Desi",
      probability: "Prob",
    },
    description: "“Designed to surprise, this machine offers a random selection with every coin. Whether it delivers a rare find or a quirky trinket, the thrill lies in the mystery of what could be waiting next.“",
    thumbnail: "./logo192.png",
    artwork: "./mov/CollectibleMalls/CollectibleMalls.mp4",
    color: "--color-future-market",
    passkit: "./passes/testwallet.pkpass",
  },
  {
    id: 2,
    weight: 0.7,
    name: "Unlimited Limited Edition",
    parent: "Collectible Malls",
    stats: {
      motivation: "Desi",
      probability: "Prob",
    },
    description: "“Meant to be rare and exclusive, this item was endlessly re-released until rarity became a fleeting illusion. Despite this, collectors still chase it, not for its scarcity but for its place in a world where exclusivity is redefined.“",
    thumbnail: "./logo192.png",
    artwork: "./mov/CollectibleMalls/CollectibleMalls.mp4",
    color: "--color-future-market",
    passkit: "./passes/testwallet.pkpass",
  },
  {
    id: 3,
    weight: 0.9,
    name: "Ordinary Collectible",
    parent: "Collectible Malls",
    stats: {
      motivation: "Desi",
      probability: "Prob",
    },
    description: "“Easily overlooked, this simple collectible has become a quiet treasure. In a world obsessed with rarity, it’s a reminder that even the ordinary can hold deep value for those who take the time to appreciate it.“",
    thumbnail: "./logo192.png",
    artwork: "./mov/CollectibleMalls/CollectibleMalls.mp4",
    color: "--color-future-market",
    passkit: "./passes/testwallet.pkpass",
  },
  {
    id: 4,
    weight: 0.6,
    name: "Artificial Hyperhype",
    parent: "Collectible Malls",
    stats: {
      motivation: "Desi",
      probability: "Prob",
    },
    description: "“Created by algorithms to spark desire, this item’s value comes not from its substance but from the attention it commands. It rises with every new wave of hype, only to fade into obscurity when the buzz dies down.“",
    thumbnail: "./logo192.png",
    artwork: "./mov/CollectibleMalls/CollectibleMalls.mp4",
    color: "--color-future-market",
    passkit: "./passes/testwallet.pkpass",
  },
  {
    id: 5,
    weight: 0.7,
    name: "Ultramega Rare Item",
    parent: "Collectible Malls",
    stats: {
      motivation: "Desi",
      probability: "Prob",
    },
    description: "“A near-mythical object, it is the ultimate prize for collectors. So rare that many doubt its existence, but for those who find it, it’s the digital crown jewel—an artifact of unparalleled status.“",
    thumbnail: "./logo192.png",
    artwork: "./mov/CollectibleMalls/CollectibleMalls.mp4",
    color: "--color-future-market",
    passkit: "./passes/testwallet.pkpass",
  },
  {
    id: 6,
    weight: 0.7,
    name: "Affection Purchase",
    parent: "Collectible Malls",
    stats: {
      motivation: "Desi",
      probability: "Prob",
    },
    description: "“Bought not for its value but for the emotion it carries, this item symbolizes a deeper connection. In a world of fleeting trends, it stands as a reminder that some things are worth more than just their price tag.“",
    thumbnail: "./logo192.png",
    artwork: "./mov/CollectibleMalls/CollectibleMalls.mp4",
    color: "--color-future-market",
    passkit: "./passes/testwallet.pkpass",
  },
  {
    id: 8,
    weight: 0.6,
    name: "Cyber Worlding",
    parent: "Cyber Worlding",
    stats: {
      motivation: "Know",
      probability: "Prob",
    },
    description: "“In a world where collecting has moved into the digital realm, collectors now explore virtual spaces where algorithms make the hunt for items effortless. With the help of emerging technologies, it's possible to experience emotions, scents, and other sensations once reserved for the physical world, making the act of collecting far more immersive.“",
    thumbnail: "./img/CyberWorlding-3.png",
    artwork: "./mov/CyberWorlding.mp4",
    color: "--color-future-digitization",
    passkit: "./passes/testwallet.pkpass",
  },
  {
    id: 10,
    weight: 0.7,
    name: "Magic Drive",
    parent: "Cyber Worlding",
    stats: {
      motivation: "Know",
      probability: "Prob",
    },
    description: "“A sleek and compact device, capable of holding an entire collection of digital items. Thanks to advanced compression technology, it can fit an entire library into a portable form, allowing collectors to carry their treasured items wherever they go, without the need for bulky storage.“",
    thumbnail: "./img/MagicDrive.png",
    artwork: "./mov/MagicDrive.mp4",
    color: "--color-future-digitization",
    passkit: "./passes/testwallet.pkpass",
  },
  {
    id: 11,
    weight: 0.5,
    name: "Rotten Hard Disk",
    parent: "Cyber Worlding",
    stats: {
      motivation: "Know",
      probability: "Prob",
    },
    description: "“At first glance, this hard disk appears to be an ordinary piece of storage, but it slowly reveals an unsettling truth about digital media: nothing lasts forever. Over time, the data deteriorates, illustrating the fragility of digital storage compared to physical archives.“",
    thumbnail: "./img/RottenHDD.png",
    artwork: "./mov/RottenHDD.mp4",
    color: "--color-future-digitization",
    passkit: "./passes/testwallet.pkpass",
  },
  {
    id: 12,
    weight: 0.6,
    name: "Algorithmic Sorter",
    parent: "Cyber Worlding",
    stats: {
      motivation: "Desi",
      probability: "Plaus",
    },
    description: "“This sophisticated algorithm curates collections based on a user’s preferences, seemingly understanding their every desire. However, despite its accuracy, it often surprises users by suggesting items that don’t quite match their true intentions, highlighting the sometimes unpredictable nature of artificial intelligence.“",
    thumbnail: "./img/AlgorithmicSorter.png",
    artwork: "./mov/AlgorithmicSorter.mp4",
    color: "--color-future-digitization",
    passkit: "./passes/testwallet.pkpass",
  },
  {
    id: 13,
    weight: 0.7,
    name: "Cloudy Weather",
    parent: "Cyber Worlding",
    stats: {
      motivation: "Desi",
      probability: "Plaus",
    },
    description: "“In the digital age, many people have chosen to store their memories and collections in the cloud, removing them from physical space. As their data floats in the digital ether, it can become overwhelming—images, media, and memories all rain down in a flood, disconnected from the tangible world they once occupied.“",
    thumbnail: "./img/CloudyWeather.png",
    artwork: "./mov/CloudyWeather.mp4",
    color: "--color-future-digitization",
    passkit: "./passes/testwallet.pkpass",
  },
  {
    id: 14,
    weight: 0.3,
    name: "( )",
    parent: "( )",
    stats: {
      motivation: "----",
      probability: "Prep",
    },
    description: "“Once, this represented the endless pursuit of something unattainable—the search that never ceased. But now, in a world where everything is already within reach, the need to collect or own anything has vanished. There is no longer any void to fill, no treasure to seek. The act of collecting has become a distant memory, replaced by a reality where everything is provided.“",
    thumbnail: "./logo192.png",
    artwork: "./mov/()/().mp4",
    color: "--color-future-none",
    passkit: "./passes/testwallet.pkpass",
  },
  {
    id: 15,
    weight: 0.4,
    name: "Motherlode",
    parent: "( )",
    stats: {
      motivation: "----",
      probability: "Prep",
    },
    description: "“In a time long past, this was the ultimate symbol of wealth, the key to untold riches. Yet, in the aftermath of a collapsing system, the hunger for money has lost all meaning. The relentless chase for more, once a defining feature of life, is now obsolete. It remains as a relic of a world that no longer values wealth, its power rendered useless in the face of a new way of life.“",
    thumbnail: "./logo192.png",
    artwork: "./mov/()/().mp4",
    color: "--color-future-none",
    passkit: "./passes/testwallet.pkpass",
  },
  {
    id: 16,
    weight: 0.3,
    name: "F.F.Food",
    parent: "( )",
    stats: {
      motivation: "----",
      probability: "Prep",
    },
    description: "“Once a crucial lifeline for survival, this is now just another convenience. In a future where food and water are no longer concerns, this has become little more than a simple choice. The struggle for nourishment is no longer a reality; instead, the focus has shifted to satisfaction, comfort, and experience. What was once vital has now become trivial.“",
    thumbnail: "./logo192.png",
    artwork: "./mov/()/().mp4",
    color: "--color-future-none",
    passkit: "./passes/testwallet.pkpass",
  },
  {
    id: 17,
    weight: 0.3,
    name: "Copilot",
    parent: "( )",
    stats: {
      motivation: "----",
      probability: "Prep",
    },
    description: "“In a time when human effort still mattered, this was a trusted companion, guiding individuals through the complexities of life. But in a world where everything is automated and pre-programmed, there is no longer any need for such assistance. Life is dictated by algorithms and routines, and this once-valuable helper now lies forgotten, overshadowed by a world that no longer requires decision-making.“",
    thumbnail: "./logo192.png",
    artwork: "./mov/()/().mp4",
    color: "--color-future-none",
    passkit: "./passes/testwallet.pkpass",
  },
  {
    id: 18,
    weight: 0.4,
    name: "All Seeing Eye",
    parent: "( )",
    stats: {
      motivation: "----",
      probability: "Plaus",
    },
    description: "“Once, this was the ultimate tool for discovering hidden truths, the key to unlocking knowledge that was once out of reach. But now, with every mind connected to a vast pool of information, nothing is hidden anymore. There is no longer a search for answers, only the constant flow of data. What once required effort to uncover is now available at the speed of thought, making this tool redundant in a world that no longer needs it.“",
    thumbnail: "./logo192.png",
    artwork: "./mov/()/().mp4",
    color: "--color-future-none",
    passkit: "./passes/testwallet.pkpass",
  },
  {
    id: 19,
    weight: 0.5,
    name: "5D-Printer",
    parent: "( )",
    stats: {
      motivation: "----",
      probability: "Plaus",
    },
    description: "“In its prime, this was a marvel of creation, capable of crafting perfect copies of anything, indistinguishable from the original. But now, in a world where anything can be reproduced at will, the concept of rarity has lost its significance. There is no longer a sense of uniqueness in ownership, as everything is replicable. The value of the original, once so cherished, has faded, leaving only an endless sea of identical copies.“",
    thumbnail: "./logo192.png",
    artwork: "./mov/()/().mp4",
    color: "--color-future-none",
    passkit: "./passes/testwallet.pkpass",
  },
  {
    id: 20,
    weight: 0.5,
    name: "Exclusive Hobby",
    parent: "Exclusive Hobby",
    stats: {
      motivation: "Desi",
      probability: "Plaus",
    },
    description: "”It sat on the shelf, a defiant object in a world that had long since abandoned the physical. To own it was an indulgence; to display it, a statement. It whispered of effort, rarity, and a love that refused to fade.“",
    thumbnail: "./logo192.png",
    artwork: "./mov/ExclusiveHobby/ExclusiveHobby.mp4",
    color: "--color-future-luxury",
    passkit: "./passes/ExclusiveHobby.pkpass",
  },
  {
    id: 21,
    weight: 0.6,
    name: "Hold your Spaces",
    parent: "Exclusive Hobby",
    stats: {
      motivation: "Surv",
      probability: "Prob",
    },
    description: "“The item occupied its spot with quiet dignity, a reminder of the room it required—a space that so few could afford. In a crowded world, it stood as proof that ownership still meant something tangible.“",
    thumbnail: "./logo192.png",
    artwork: "./mov/ExclusiveHobby/HoldYourSpaces.mp4",
    color: "--color-future-luxury",
    passkit: "./passes/testwallet.pkpass",
  },
  {
    id: 22,
    weight: 0.4,
    name: "Silk Road Parcel",
    parent: "Exclusive Hobby",
    stats: {
      motivation: "Desi",
      probability: "Plaus",
    },
    description: "“The parcel bore the marks of a long and arduous journey, its edges softened by hands and time. It was a survivor of fractured trade and impossible costs, and now it rested here—a testament to perseverance.“",
    thumbnail: "./logo192.png",
    artwork: "./mov/ExclusiveHobby/SilkroadParcel.mp4",
    color: "--color-future-luxury",
    passkit: "./passes/testwallet.pkpass",
  },
  {
    id: 23,
    weight: 0.4,
    name: "Inflated Bread",
    parent: "Exclusive Hobby",
    stats: {
      motivation: "Surv",
      probability: "Plaus",
    },
    description: "“Round, swollen, and impossibly light, it looked more like a symbol than sustenance. Once, it might have fed a family; now, it tells the story of a world where even bread became a luxury few could afford.“",
    thumbnail: "./logo192.png",
    artwork: "./mov/ExclusiveHobby/InflatedBread.mp4",
    color: "--color-future-luxury",
    passkit: "./passes/testwallet.pkpass",
  },
  {
    id: 24,
    weight: 0.6,
    name: "Private Aura, Public Viewing",
    parent: "Exclusive Hobby",
    stats: {
      motivation: "Know",
      probability: "Plaus",
    },
    description: "“Onlookers marveled at its form, drawn to its presence, but there was something they couldn’t grasp. It had a gravity that screens could never capture, a physicality that made it irreplaceable. They could look, but only one could truly hold it.“",
    thumbnail: "./logo192.png",
    artwork: "./mov/ExclusiveHobby/PrivateAura.mp4",
    color: "--color-future-luxury",
    passkit: "./passes/testwallet.pkpass",
  },
  {
    id: 26,
    weight: 0.4,
    name: "Gather or Die",
    parent: "Gather or Die",
    stats: {
      motivation: "Surv",
      probability: "Plaus",
    },
    description: "“In a world where survival is a constant struggle, this relic became a grim reminder that gathering was no longer optional. Those who could collect resources—no matter how small—thrived, while those who couldn’t were left to fade into obscurity. It became a harsh mantra: gather, or perish.“",
    thumbnail: "./logo192.png",
    artwork: "./mov/GatherOrDie/GatherOrDie.mp4",
    color: "--color-future-survival",
    passkit: "./passes/testwallet.pkpass",
  },
  {
    id: 27,
    weight: 0.6,
    name: "Prepper Paradise",
    parent: "Gather or Die",
    stats: {
      motivation: "Desi",
      probability: "Prob",
    },
    description: "“What began as a simple hobby quickly transformed into something much more crucial. In a world teetering on the edge, it offered a way to prepare for any disaster. It was a sanctuary for those who feared the worst, a collection of tools, food, and knowledge that would ensure survival in times of need.“",
    thumbnail: "./logo192.png",
    artwork: "./mov/GatherOrDie/GatherOrDie.mp4",
    color: "--color-future-survival",
    passkit: "./passes/testwallet.pkpass",
  },
  {
    id: 28,
    weight: 0.5,
    name: "Genetically Manipulated Crops",
    parent: "Gather or Die",
    stats: {
      motivation: "Surv",
      probability: "Plaus",
    },
    description: "“Born from humanity’s desperate attempts to control nature, these crops were engineered to survive even the most hostile environments. The scientists who created them collected every scrap of genetic knowledge they could, hoping that these crops would offer a chance for survival, but knowing the risks that came with tampering with nature.“",
    thumbnail: "./logo192.png",
    artwork: "./mov/GatherOrDie/GatherOrDie.mp4",
    color: "--color-future-survival",
    passkit: "./passes/testwallet.pkpass",
  },
  {
    id: 29,
    weight: 0.3,
    name: "Ground Zero Remains",
    parent: "Gather or Die",
    stats: {
      motivation: "Surv",
      probability: "Prep",
    },
    description: "“Once the symbol of devastation, the radioactive remains from an ancient catastrophe became something else entirely. What was once feared as toxic and dangerous was now collected and stored carefully, its energy harnessed for the rebuilding of a broken world. What was once deadly was now a valuable resource in the struggle to move forward.“",
    thumbnail: "./logo192.png",
    artwork: "./mov/GatherOrDie/GatherOrDie.mp4",
    color: "--color-future-survival",
    passkit: "./passes/testwallet.pkpass",
  },
  {
    id: 30,
    weight: 0.2,
    name: "Noah's Ark",
    parent: "Gather or Die",
    stats: {
      motivation: "Surv",
      probability: "Prep",
    },
    description: "“Much like the fabled story of old, this sanctuary held the last remnants of the world’s creatures. Carefully preserved genetic samples from plants and animals were stored with the hope that life could be reborn. The keeper of this collection carried the heavy responsibility of ensuring that, one day, the world might be restored to its former balance.“",
    thumbnail: "./logo192.png",
    artwork: "./mov/GatherOrDie/GatherOrDie.mp4",
    color: "--color-future-survival",
    passkit: "./passes/testwallet.pkpass",
  },
  {
    id: 31,
    weight: 0.7,
    name: "Savior Vault",
    parent: "Gather or Die",
    stats: {
      motivation: "Know",
      probability: "Prob",
    },
    description: "“Beneath layers of earth and time, these vaults housed the last chance for a future. Contained within were the seeds and DNA of a world lost, a legacy meant to survive beyond the apocalyptic collapse. Those who knew of them understood that unlocking their contents was humanity's best hope for starting over.“",
    thumbnail: "./logo192.png",
    artwork: "./mov/GatherOrDie/GatherOrDie.mp4",
    color: "--color-future-survival",
    passkit: "./passes/testwallet.pkpass",
  },
];