export const items = [
  {
    id: 1,
    weight: 0.2,
    name: "Mystery Vending Machine",
    parent: "Collectible Malls",
    stats: {
      motivation: "Sur",
      probability: "Pla",
    },
    description: "“Forged in the ashes of a fallen world, this all-purpose tool is a lifeline to ancient survival. Forged in the ashes of a fallen world, this all-purpose tool is a lifeline to ancient survival. Its blade cuts through wood and bone, its groove strikes fire from stone, and its grip carries the spirit of those who fought to endure. With every use, it reminds its bearer: survival is not just a skill, but a legacy.”",
    thumbnail: "./logo192.png",
    artwork: "./test.mp4",
    color: "--color-future-market",
    passkit: "./passes/testwallet.pkpass",
  },
  {
    id: 2,
    weight: 0.4,
    name: "Unlimited Limited Edition",
    parent: "Collectible Malls",
    stats: {
      motivation: "Kno",
      probability: "Pla",
    },
    description: "Forged in the ashes of a fallen world, this all-purpose tool is a lifeline to ancient survival. Its blade cuts through wood and bone, its groove strikes fire from stone, and its grip carries the spirit of those who fought to endure. With every use, it reminds its bearer: survival is not just a skill, but a legacy.”",
    thumbnail: "./logo192.png",
    artwork: "./test.mp4",
    color: "--color-future-market",
    passkit: "./passes/testwallet.pkpass",
  },
  {
    id: 3,
    weight: 0.9,
    name: "Ordinary Collectible",
    parent: "Collectible Malls",
    stats: {
      motivation: "Kno",
      probability: "Pla",
    },
    description: "Forged in the ashes of a fallen world, this all-purpose tool is a lifeline to ancient survival. Its blade cuts through wood and bone, its groove strikes fire from stone, and its grip carries the spirit of those who fought to endure. With every use, it reminds its bearer: survival is not just a skill, but a legacy.”",
    thumbnail: "./logo192.png",
    artwork: "./download.mp4",
    color: "--color-future-market",
    passkit: "./passes/testwallet.pkpass",
  },
  {
    id: 4,
    weight: 0.2,
    name: "Artificial Hyperhype",
    parent: "Collectible Malls",
    stats: {
      motivation: "Kno",
      probability: "Pla",
    },
    description: "Forged in the ashes of a fallen world, this all-purpose tool is a lifeline to ancient survival. Its blade cuts through wood and bone, its groove strikes fire from stone, and its grip carries the spirit of those who fought to endure. With every use, it reminds its bearer: survival is not just a skill, but a legacy.”",
    thumbnail: "./logo192.png",
    artwork: "./test.mp4",
    color: "--color-future-market",
    passkit: "./passes/testwallet.pkpass",
  },
  {
    id: 5,
    weight: 0.1,
    name: "Ultramega Rare Item",
    parent: "Collectible Malls",
    stats: {
      motivation: "Kno",
      probability: "Pla",
    },
    description: "Forged in the ashes of a fallen world, this all-purpose tool is a lifeline to ancient survival. Its blade cuts through wood and bone, its groove strikes fire from stone, and its grip carries the spirit of those who fought to endure. With every use, it reminds its bearer: survival is not just a skill, but a legacy.”",
    thumbnail: "./logo192.png",
    artwork: "./test.mp4",
    color: "--color-future-market",
    passkit: "./passes/testwallet.pkpass",
  },
  {
    id: 6,
    weight: 0.7,
    name: "Affection Purchase",
    parent: "Collectible Malls",
    stats: {
      motivation: "Kno",
      probability: "Pla",
    },
    description: "Forged in the ashes of a fallen world, this all-purpose tool is a lifeline to ancient survival. Its blade cuts through wood and bone, its groove strikes fire from stone, and its grip carries the spirit of those who fought to endure. With every use, it reminds its bearer: survival is not just a skill, but a legacy.”",
    thumbnail: "./logo192.png",
    artwork: "./test.mp4",
    color: "--color-future-market",
    passkit: "./passes/testwallet.pkpass",
  },
  {
    id: 7,
    weight: 0.5,
    name: "Collectible Malls",
    parent: "Collectible Malls",
    stats: {
      motivation: "Kno",
      probability: "Pla",
    },
    description: "Forged in the ashes of a fallen world, this all-purpose tool is a lifeline to ancient survival. Its blade cuts through wood and bone, its groove strikes fire from stone, and its grip carries the spirit of those who fought to endure. With every use, it reminds its bearer: survival is not just a skill, but a legacy.”",
    thumbnail: "./logo192.png",
    artwork: "./test.mp4",
    color: "--color-future-market",
    passkit: "./passes/testwallet.pkpass",
  },
  {
    id: 8,
    weight: 0.5,
    name: "Cyber Worlding",
    parent: "Cyber Worlding",
    stats: {
      motivation: "Kno",
      probability: "Pla",
    },
    description: "Forged in the ashes of a fallen world, this all-purpose tool is a lifeline to ancient survival. Its blade cuts through wood and bone, its groove strikes fire from stone, and its grip carries the spirit of those who fought to endure. With every use, it reminds its bearer: survival is not just a skill, but a legacy.”",
    thumbnail: "./img/CyberWorlding.png",
    artwork: "./mov/CyberWorlding.mp4",
    color: "--color-future-digitization",
    passkit: "./passes/testwallet.pkpass",
  },
  {
    id: 9,
    weight: 0.5,
    name: "HAL 10000",
    parent: "Cyber Worlding",
    stats: {
      motivation: "Kno",
      probability: "Pla",
    },
    description: "Forged in the ashes of a fallen world, this all-purpose tool is a lifeline to ancient survival. Its blade cuts through wood and bone, its groove strikes fire from stone, and its grip carries the spirit of those who fought to endure. With every use, it reminds its bearer: survival is not just a skill, but a legacy.”",
    thumbnail: "./img/HAL10000.png",
    artwork: "./mov/HAL10000.mp4",
    color: "--color-future-digitization",
    passkit: "./passes/hal10000.pkpass",
  },
  {
    id: 10,
    weight: 0.5,
    name: "Item 3",
    parent: "Cyber Worlding",
    stats: {
      motivation: "Kno",
      probability: "Pla",
    },
    description: "Forged in the ashes of a fallen world, this all-purpose tool is a lifeline to ancient survival. Its blade cuts through wood and bone, its groove strikes fire from stone, and its grip carries the spirit of those who fought to endure. With every use, it reminds its bearer: survival is not just a skill, but a legacy.”",
    thumbnail: "./img/CyberWorlding.png",
    artwork: "./mov/CyberWorlding.mp4",
    color: "--color-future-digitization",
    passkit: "./passes/testwallet.pkpass",
  },
  {
    id: 11,
    weight: 0.5,
    name: "Item 4",
    parent: "Cyber Worlding",
    stats: {
      motivation: "Kno",
      probability: "Pla",
    },
    description: "Forged in the ashes of a fallen world, this all-purpose tool is a lifeline to ancient survival. Its blade cuts through wood and bone, its groove strikes fire from stone, and its grip carries the spirit of those who fought to endure. With every use, it reminds its bearer: survival is not just a skill, but a legacy.”",
    thumbnail: "./img/CyberWorlding.png",
    artwork: "./mov/CyberWorlding.mp4",
    color: "--color-future-digitization",
    passkit: "./passes/testwallet.pkpass",
  },
  {
    id: 12,
    weight: 0.5,
    name: "Item 5",
    parent: "Cyber Worlding",
    stats: {
      motivation: "Kno",
      probability: "Pla",
    },
    description: "Forged in the ashes of a fallen world, this all-purpose tool is a lifeline to ancient survival. Its blade cuts through wood and bone, its groove strikes fire from stone, and its grip carries the spirit of those who fought to endure. With every use, it reminds its bearer: survival is not just a skill, but a legacy.”",
    thumbnail: "./img/CyberWorlding.png",
    artwork: "./mov/CyberWorlding.mp4",
    color: "--color-future-digitization",
    passkit: "./passes/testwallet.pkpass",
  },
  {
    id: 13,
    weight: 0.5,
    name: "Item 6",
    parent: "Cyber Worlding",
    stats: {
      motivation: "Kno",
      probability: "Pla",
    },
    description: "Forged in the ashes of a fallen world, this all-purpose tool is a lifeline to ancient survival. Its blade cuts through wood and bone, its groove strikes fire from stone, and its grip carries the spirit of those who fought to endure. With every use, it reminds its bearer: survival is not just a skill, but a legacy.”",
    thumbnail: "./img/CyberWorlding.png",
    artwork: "./mov/CyberWorlding.mp4",
    color: "--color-future-digitization",
    passkit: "./passes/testwallet.pkpass",
  },
  {
    id: 14,
    weight: 0.5,
    name: "( )",
    parent: "( )",
    stats: {
      motivation: "Kno",
      probability: "Pla",
    },
    description: "Forged in the ashes of a fallen world, this all-purpose tool is a lifeline to ancient survival. Its blade cuts through wood and bone, its groove strikes fire from stone, and its grip carries the spirit of those who fought to endure. With every use, it reminds its bearer: survival is not just a skill, but a legacy.”",
    thumbnail: "./logo192.png",
    artwork: "./test.mp4",
    color: "--color-future-none",
    passkit: "./passes/testwallet.pkpass",
  },
  {
    id: 15,
    weight: 0.5,
    name: "Item 2",
    parent: "( )",
    stats: {
      motivation: "Kno",
      probability: "Pla",
    },
    description: "Forged in the ashes of a fallen world, this all-purpose tool is a lifeline to ancient survival. Its blade cuts through wood and bone, its groove strikes fire from stone, and its grip carries the spirit of those who fought to endure. With every use, it reminds its bearer: survival is not just a skill, but a legacy.”",
    thumbnail: "./logo192.png",
    artwork: "./test.mp4",
    color: "--color-future-none",
    passkit: "./passes/testwallet.pkpass",
  },
  {
    id: 16,
    weight: 0.5,
    name: "Item 3",
    parent: "( )",
    stats: {
      motivation: "Kno",
      probability: "Pla",
    },
    description: "Forged in the ashes of a fallen world, this all-purpose tool is a lifeline to ancient survival. Its blade cuts through wood and bone, its groove strikes fire from stone, and its grip carries the spirit of those who fought to endure. With every use, it reminds its bearer: survival is not just a skill, but a legacy.”",
    thumbnail: "./logo192.png",
    artwork: "./test.mp4",
    color: "--color-future-none",
    passkit: "./passes/testwallet.pkpass",
  },
  {
    id: 17,
    weight: 0.5,
    name: "Item 4",
    parent: "( )",
    stats: {
      motivation: "Kno",
      probability: "Pla",
    },
    description: "Forged in the ashes of a fallen world, this all-purpose tool is a lifeline to ancient survival. Its blade cuts through wood and bone, its groove strikes fire from stone, and its grip carries the spirit of those who fought to endure. With every use, it reminds its bearer: survival is not just a skill, but a legacy.”",
    thumbnail: "./logo192.png",
    artwork: "./test.mp4",
    color: "--color-future-none",
    passkit: "./passes/testwallet.pkpass",
  },
  {
    id: 18,
    weight: 0.5,
    name: "Item 5",
    parent: "( )",
    stats: {
      motivation: "Kno",
      probability: "Pla",
    },
    description: "Forged in the ashes of a fallen world, this all-purpose tool is a lifeline to ancient survival. Its blade cuts through wood and bone, its groove strikes fire from stone, and its grip carries the spirit of those who fought to endure. With every use, it reminds its bearer: survival is not just a skill, but a legacy.”",
    thumbnail: "./logo192.png",
    artwork: "./test.mp4",
    color: "--color-future-none",
    passkit: "./passes/testwallet.pkpass",
  },
  {
    id: 19,
    weight: 0.5,
    name: "Item 6",
    parent: "( )",
    stats: {
      motivation: "Kno",
      probability: "Pla",
    },
    description: "Forged in the ashes of a fallen world, this all-purpose tool is a lifeline to ancient survival. Its blade cuts through wood and bone, its groove strikes fire from stone, and its grip carries the spirit of those who fought to endure. With every use, it reminds its bearer: survival is not just a skill, but a legacy.”",
    thumbnail: "./logo192.png",
    artwork: "./test.mp4",
    color: "--color-future-none",
    passkit: "./passes/testwallet.pkpass",
  },
  {
    id: 20,
    weight: 0.5,
    name: "Exclusive Hobby",
    parent: "Exclusive Hobby",
    stats: {
      motivation: "Kno",
      probability: "Pla",
    },
    description: "Forged in the ashes of a fallen world, this all-purpose tool is a lifeline to ancient survival. Its blade cuts through wood and bone, its groove strikes fire from stone, and its grip carries the spirit of those who fought to endure. With every use, it reminds its bearer: survival is not just a skill, but a legacy.”",
    thumbnail: "./logo192.png",
    artwork: "./test.mp4",
    color: "--color-future-luxury",
    passkit: "./passes/testwallet.pkpass",
  },
  {
    id: 21,
    weight: 0.5,
    name: "Item 2",
    parent: "Exclusive Hobby",
    stats: {
      motivation: "Kno",
      probability: "Pla",
    },
    description: "Forged in the ashes of a fallen world, this all-purpose tool is a lifeline to ancient survival. Its blade cuts through wood and bone, its groove strikes fire from stone, and its grip carries the spirit of those who fought to endure. With every use, it reminds its bearer: survival is not just a skill, but a legacy.”",
    thumbnail: "./logo192.png",
    artwork: "./test.mp4",
    color: "--color-future-luxury",
    passkit: "./passes/testwallet.pkpass",
  },
  {
    id: 22,
    weight: 0.5,
    name: "Item 3",
    parent: "Exclusive Hobby",
    stats: {
      motivation: "Kno",
      probability: "Pla",
    },
    description: "Forged in the ashes of a fallen world, this all-purpose tool is a lifeline to ancient survival. Its blade cuts through wood and bone, its groove strikes fire from stone, and its grip carries the spirit of those who fought to endure. With every use, it reminds its bearer: survival is not just a skill, but a legacy.”",
    thumbnail: "./logo192.png",
    artwork: "./test.mp4",
    color: "--color-future-luxury",
    passkit: "./passes/testwallet.pkpass",
  },
  {
    id: 23,
    weight: 0.5,
    name: "Item 4",
    parent: "Exclusive Hobby",
    stats: {
      motivation: "Kno",
      probability: "Pla",
    },
    description: "Forged in the ashes of a fallen world, this all-purpose tool is a lifeline to ancient survival. Its blade cuts through wood and bone, its groove strikes fire from stone, and its grip carries the spirit of those who fought to endure. With every use, it reminds its bearer: survival is not just a skill, but a legacy.”",
    thumbnail: "./logo192.png",
    artwork: "./test.mp4",
    color: "--color-future-luxury",
    passkit: "./passes/testwallet.pkpass",
  },
  {
    id: 24,
    weight: 0.5,
    name: "Item 5",
    parent: "Exclusive Hobby",
    stats: {
      motivation: "Kno",
      probability: "Pla",
    },
    description: "Forged in the ashes of a fallen world, this all-purpose tool is a lifeline to ancient survival. Its blade cuts through wood and bone, its groove strikes fire from stone, and its grip carries the spirit of those who fought to endure. With every use, it reminds its bearer: survival is not just a skill, but a legacy.”",
    thumbnail: "./logo192.png",
    artwork: "./test.mp4",
    color: "--color-future-luxury",
    passkit: "./passes/testwallet.pkpass",
  },
  {
    id: 25,
    weight: 0.5,
    name: "Item 6",
    parent: "Exclusive Hobby",
    stats: {
      motivation: "Kno",
      probability: "Pla",
    },
    description: "Forged in the ashes of a fallen world, this all-purpose tool is a lifeline to ancient survival. Its blade cuts through wood and bone, its groove strikes fire from stone, and its grip carries the spirit of those who fought to endure. With every use, it reminds its bearer: survival is not just a skill, but a legacy.”",
    thumbnail: "./logo192.png",
    artwork: "./test.mp4",
    color: "--color-future-luxury",
    passkit: "./passes/testwallet.pkpass",
  },
  {
    id: 26,
    weight: 0.5,
    name: "Gather or Die",
    parent: "Gather or Die",
    stats: {
      motivation: "Kno",
      probability: "Pla",
    },
    description: "Forged in the ashes of a fallen world, this all-purpose tool is a lifeline to ancient survival. Its blade cuts through wood and bone, its groove strikes fire from stone, and its grip carries the spirit of those who fought to endure. With every use, it reminds its bearer: survival is not just a skill, but a legacy.”",
    thumbnail: "./logo192.png",
    artwork: "./test.mp4",
    color: "--color-future-survival",
    passkit: "./passes/testwallet.pkpass",
  },
  {
    id: 27,
    weight: 0.5,
    name: "Item 2",
    parent: "Gather or Die",
    stats: {
      motivation: "Kno",
      probability: "Pla",
    },
    description: "Forged in the ashes of a fallen world, this all-purpose tool is a lifeline to ancient survival. Its blade cuts through wood and bone, its groove strikes fire from stone, and its grip carries the spirit of those who fought to endure. With every use, it reminds its bearer: survival is not just a skill, but a legacy.”",
    thumbnail: "./logo192.png",
    artwork: "./test.mp4",
    color: "--color-future-survival",
    passkit: "./passes/testwallet.pkpass",
  },
  {
    id: 28,
    weight: 0.5,
    name: "Item 3",
    parent: "Gather or Die",
    stats: {
      motivation: "Kno",
      probability: "Pla",
    },
    description: "Forged in the ashes of a fallen world, this all-purpose tool is a lifeline to ancient survival. Its blade cuts through wood and bone, its groove strikes fire from stone, and its grip carries the spirit of those who fought to endure. With every use, it reminds its bearer: survival is not just a skill, but a legacy.”",
    thumbnail: "./logo192.png",
    artwork: "./test.mp4",
    color: "--color-future-survival",
    passkit: "./passes/testwallet.pkpass",
  },
  {
    id: 29,
    weight: 0.5,
    name: "Item 4",
    parent: "Gather or Die",
    stats: {
      motivation: "Kno",
      probability: "Pla",
    },
    description: "Forged in the ashes of a fallen world, this all-purpose tool is a lifeline to ancient survival. Its blade cuts through wood and bone, its groove strikes fire from stone, and its grip carries the spirit of those who fought to endure. With every use, it reminds its bearer: survival is not just a skill, but a legacy.”",
    thumbnail: "./logo192.png",
    artwork: "./test.mp4",
    color: "--color-future-survival",
    passkit: "./passes/testwallet.pkpass",
  },
  {
    id: 30,
    weight: 0.5,
    name: "Item 5",
    parent: "Gather or Die",
    stats: {
      motivation: "Kno",
      probability: "Pla",
    },
    description: "Forged in the ashes of a fallen world, this all-purpose tool is a lifeline to ancient survival. Its blade cuts through wood and bone, its groove strikes fire from stone, and its grip carries the spirit of those who fought to endure. With every use, it reminds its bearer: survival is not just a skill, but a legacy.”",
    thumbnail: "./logo192.png",
    artwork: "./test.mp4",
    color: "--color-future-survival",
    passkit: "./passes/testwallet.pkpass",
  },
  {
    id: 31,
    weight: 0.5,
    name: "Item 6",
    parent: "Gather or Die",
    stats: {
      motivation: "Kno",
      probability: "Pla",
    },
    description: "Forged in the ashes of a fallen world, this all-purpose tool is a lifeline to ancient survival. Its blade cuts through wood and bone, its groove strikes fire from stone, and its grip carries the spirit of those who fought to endure. With every use, it reminds its bearer: survival is not just a skill, but a legacy.”",
    thumbnail: "./logo192.png",
    artwork: "./test.mp4",
    color: "--color-future-survival",
    passkit: "./passes/testwallet.pkpass",
  },
];